version: '3.5'

# Example stack for local development
# IMPORTANT: you need to create the docker images first via gradle like this:
# ./gradlew buildDockerImage

services:
  signpdf:
    image: lovelysystems/signpdf:dev
    ports:
     - "18080:8080"
    environment:
      # optional environment variable set here to their defaults for reference
      KEYSTORE_PASS_PATH: /run/secrets/signpdf-keystore-pass
      KEYSTORE_PATH: /run/secrets/signpdf-keystore
      PORT: 8080
    secrets:
     - signpdf-keystore
     - signpdf-keystore-pass

secrets:
   signpdf-keystore:
     file: ../src/test/resources/com/lovelysystems/signpdf/samplekeystore.p12
   signpdf-keystore-pass:
     file: ../src/test/resources/com/lovelysystems/signpdf/samplekeystorepass.txt
